{"name": "6. если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "parameters": [{"name": "api", "value": "'api/v1/courier'"}, {"name": "code", "value": "'{\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}'"}], "start": 1723485857948, "stop": 1723485858313, "uuid": "11eda097-43aa-428e-a790-9660ae2b7f1d", "historyId": "e6fe26db66098bffb8be9e8ed19f6daf", "testCaseId": "2ac4610ba53332d6a4989d919b0850db", "fullName": "tests.test_account.TestApi#test_failed_create_copy_account", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_account"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "dim"}, {"name": "thread", "value": "6073-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_account"}]}