{"name": "6. если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "parameters": [{"name": "api", "value": "'api/v1/courier'"}, {"name": "code", "value": "'{\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}'"}], "start": 1723380083621, "stop": 1723380084022, "uuid": "218ba32e-fdf6-427a-b954-51112b16fe4c", "historyId": "79465dd4bb4b1aa61a8e69fd51d1d5d0", "testCaseId": "dd88f046bb74cf933f0e8d53de67ae6c", "fullName": "tests.create_account.TestApi#test_failed_create_copy_account", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "create_account"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "dim"}, {"name": "thread", "value": "8910-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.create_account"}]}